# vim ft=yaml
# travis-ci.org definition

sudo: false
dist: trusty

language: cpp
compiler:
  - gcc
cache:
  - apt
  - ccache

env:
  matrix:
    - GCC_VERSION=5
    - GCC_VERSION=6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
# below requires https://github.com/travis-ci/apt-source-whitelist/pull/309
#      - llvm-toolchain-trusty-3.8
#      - llvm-toolchain-trusty-3.9
# llvm urls awaiting fix
# https://github.com/travis-ci/apt-source-whitelist/pull/288
# https://github.com/travis-ci/apt-source-whitelist/pull/309
    packages: # make sure these match debian/control contents
      - gcc-5
      - g++-5
      - gcc-6
      - g++-6
      - bison
      - chrpath
      - cmake
      - debhelper
      - dh-apparmor
      - dpatch
      - gdb
      - libaio-dev
      - libboost-dev
      - libjudy-dev
      - libncurses5-dev
      - libpam0g-dev
      - libpcre3-dev
      - libreadline-gplv2-dev
      - libstemmer-dev
      - libssl-dev
      - libnuma-dev
      - libxml2-dev
      - lsb-release
      - perl
      - po-debconf
      - psmisc
      - zlib1g-dev
      - libcrack2-dev
      - libjemalloc-dev
      - devscripts # implicit for any build on Ubuntu

# Can't do sudo: false with full list of packages until:
# https://github.com/travis-ci/apt-package-whitelist/issues/3673 gdb
# https://github.com/travis-ci/apt-package-whitelist/issues/3677 libreadline-gplv2-dev
# https://github.com/travis-ci/apt-package-whitelist/issues/3945 libcrack2-dev
# https://github.com/travis-ci/apt-package-whitelist/issues/3944 libsystemd-daemon-dev

script:
  - export MYSQL_BUILD_CC=/usr/bin/gcc-${GCC_VERSION} MYSQL_BUILD_CXX=/usr/bin/g++-${GCC_VERSION} MYSQL_COMPILER_LAUNCHER=ccache
  - ${MYSQL_BUILD_CC} --version ; ${MYSQL_BUILD_CXX} --version
  - cd "${TRAVIS_BUILD_DIR}"
# https://github.com/travis-ci/travis-ci/issues/7062 - /run/shm isn't writable in trusty containers
#  - export MTR_MEM=/dev/shm
  - ccache --zero-stats
  - env DEB_BUILD_OPTIONS="parallel=3" debian/autobake-deb.sh;
  - ccache --show-stats

notifications:
  irc:
    channels:
      - "chat.freenode.net#maria"
    on_success: never # [always|never|change]
    on_failure: never
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
