# vim ft=yaml
# travis-ci.org definition

# non-container builds don't have enough RAM to reliably compile
sudo: false
dist: trusty

language: cpp
compiler:
  - gcc
cache:
  - apt
  - ccache

env:
  matrix:
    - COMPILER=gcc-4.8
    - COMPILER=gcc-5
    - COMPILER=gcc-6
    - COMPILER=clang-3.6
    - COMPILER=clang-3.9
    - COMPILER=clang-4.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
    packages: # make sure these match debian/control contents
      - gcc-5
      - g++-5
      - gcc-6
      - g++-6
      - clang-3.6
      - clang-3.9
      - clang-4.0
      - bison
      - chrpath
      - cmake
      - debhelper
      - dh-apparmor
      - dpatch
      - gdb
      - libaio-dev
      - libboost-dev
      - libjudy-dev
      - libncurses5-dev
      - libpam0g-dev
      - libpcre3-dev
      - libreadline-gplv2-dev
      - libstemmer-dev
      - libssl-dev
      - libnuma-dev
      - libxml2-dev
      - lsb-release
      - perl
      - po-debconf
      - psmisc
      - zlib1g-dev
      - libcrack2-dev
      - libjemalloc-dev
      - devscripts # implicit for any build on Ubuntu

# libsnappy-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3880
# liblzma-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3879
# libzmq-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3881
# libsystemd-daemon-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3882

script:
  - export MYSQL_BUILD_CC=/usr/bin/${COMPILER} MYSQL_COMPILER_LAUNCHER=ccache
  - case $COMPILER in gcc*) export MYSQL_BUILD_CXX=/usr/bin/${COMPILER/cc/++} ;; clang*) export MYSQL_BUILD_CXX=/usr/bin/${COMPILER/-/++-} ;; esac
  - ${MYSQL_BUILD_CC} --version ; ${MYSQL_BUILD_CXX} --version
  - cd "${TRAVIS_BUILD_DIR}"
  - env DEB_BUILD_OPTIONS="parallel=3" debian/autobake-deb.sh;

notifications:
  irc:
    channels:
      - "chat.freenode.net#maria"
    on_success: never # [always|never|change]
    on_failure: never
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
